spring.application.name=Demo-Project-on-Automation-of-Hanging-Accounts

# Main DB = PostgreSQL
spring.datasource.jdbc-url=jdbc:postgresql://localhost:5432/hanging_accounts
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Oracle Source DB
oracle.datasource.jdbc-url=jdbc:oracle:thin:@192.168.10.46:1521/ORCL
oracle.datasource.username=system
oracle.datasource.password=oracle
oracle.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
